apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ecommerce-deployment
  labels:
    app: flask-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ecommerce
  template:
    metadata:
      labels:
        app: flask-ecommerce
    spec:
      containers:
        - name: flask-ecommerce
          image: davidjosva/flask-ecommerce:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: PORT
              value: "5000"
