apiVersion: v1
kind: Service
metadata:
  name: flask-ecommerce-service
  labels:
    app: flask-ecommerce
spec:
  type: NodePort
  selector:
    app: flask-ecommerce
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
